name: Generate Bundles

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update pkg-config database
        run: sudo ldconfig
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build ffmpeg-core
        run: make prd